maintab_LAST = local
screen_h = 1009
window_maximized = false
screen_w = 1920
menu_last_game = mineclone2
enable_damage = true
creative_mode = true
mainmenu_last_selected_world = 1
enable_fog = true
free_move = true
mcl_enable_hunger = true
vl_creative_instant_kill = true
server_announce = false
mcl_mobs_open_gates = true
show_advanced = true
show_technical_names = false
fullscreen = true
vl_christmas_decorations = Never
enable_server = false
address = crabdance.minetest.land
name = me
remote_port = 30000
